// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://knhrjsrtxaehqkrusumy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtuaHJqc3J0eGFlaHFrcnVzdW15Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2OTkwMjEsImV4cCI6MjA2NjI3NTAyMX0.Q_D_BPyypMParb-oXY2xUNbmo2l16XMZrwaIR7TyOaQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);